#!/usr/bin/env sh
set -eu

DEPENDENCIES=curl

apk --no-cache add ${DEPENDENCIES}
curl -SL https://api.github.com/repos/dockage/runit-scripts/tarball > runit-scripts.tar.gz

tar -xzvf runit-scripts.tar.gz
cp -ar /dockage-runit-scripts-*/alpine/etc/* /etc
cp -ar /dockage-runit-scripts-*/alpine/usr/* /usr

# Clean up
rm -rf /dockage-runit-scripts-* runit-scripts.tar.gz
apk del ${DEPENDENCIES}