#!/usr/bin/env sh
set -eu

exec 2>&1

DAEMON=/usr/sbin/nginx

# Check nginx command is executable or not
test -x ${DAEMON} || exit 0

# Test nginx configuration
${COMMAND} -t -q || exit 0

mkdir -p /var/log/nginx

exec ${DAEMON} -c /etc/nginx/nginx.conf -g "daemon off;"