#!/usr/bin/env sh
set -eu

exec 2>&1

DAEMON=/usr/sbin/php5-fpm

test -x ${DAEMON} || exit 0
/usr/lib/php5/php5-fpm-checkconf || (echo 'php5-fpm config has error.' && exit 1)

exec ${DAEMON} --nodaemonize --force-stderr --fpm-config /etc/php5/fpm/php-fpm.conf